sudo: required
services:
  - docker

before_install:
  - docker build -t sinanuyar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sinanuyar/react-test npm test

after_success:
  - docker build -t sinanuyar/multi-client ./client
  - docker build -t sinanuyar/multi-nginx ./nginx
  - docker build -t sinanuyar/multi-server ./server
  - docker build -t sinanuyar/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push  sinanuyar/multi-client
  - docker push  sinanuyar/multi-nginx
  - docker push  sinanuyar/multi-server
  - docker push  sinanuyar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker-training"
  env: "Multidockertraining-env"
  bucket_name: "elasticbeanstalk-us-east-1-386914680837"
  bucket_path: "multi-docker-training"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY